### PR TITLE
Add default for object_interacted

### PR DESCRIPTION
**Pull request by shuabritze**

### CODE REVIEW

**Comment by kOchirasu** [comment]
did you regenerate this? after adding a default value, any script specifying the same value will drop it.

**Comment by kOchirasu** [comment]
oh i see, it used to be marked required. why make it optional?

**Comment by shuabritze** [comment]
Some trigger scripts don't specify the parameter:
```python
Scripts\Trigger\02000331_bf\seeker01.py

    def on_tick(self) -> trigger_api.Trigger:
        if self.object_interacted(interact_ids=[10000785]):
            return 외다리생성시작01(self.ctx)
```

**Comment by kOchirasu** [comment]
hmm, there must be a bug then because marking required should validate that the field is always set.

**Comment by shuabritze** [comment]
TriggerScript.Condition.cs was missing the check for required types in the WriteTo method

**Pull request merged**
